name: API

on:
  pull_request:
    branches:
      - main

jobs:
  run-api:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Download openapi cli
        run: curl https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.7.0/openapi-generator-cli-7.7.0.jar -o openapi-generator-cli.jar

      - name: API Merchant validation
        run: java -jar openapi-generator-cli.jar validate -i api-merchant.yaml --recommend

#      - name: Generate API Merchant documentation
#        run: |
#          java -jar openapi-generator-cli.jar generate -i api-merchant.yaml \
#            -g html2 -o docs
