name: Generate documentation

on:
  pull_request:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest
#    permissions:
#      contents: write
    steps:
      - name: Git clone
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Download openapi cli
        run: curl https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.7.0/openapi-generator-cli-7.7.0.jar -o openapi-generator-cli.jar

      - name: Validation API
        run: java -jar openapi-generator-cli.jar validate -i api-merchant.yaml --recommend

      - name: Generate documentation
        run: |
          rm -rf docs
          java -jar openapi-generator-cli.jar generate -i api-merchant.yaml -g html2 -o docs

      - name: Remove generator (openapi cli)
        run: rm -rf openapi-generator-cli.jar

      - name: Commit generated documentation
        uses: EndBug/add-and-commit@v9
        with:
          message: Commit generated documentation
