name: Cancel

on:
  pull_request:
    branches:
      - main

jobs:
  cancel-job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      actions: write
    steps:
      - name: API
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          workflow_id: api.yml
          access_token: ${{ secrets.GITHUB_TOKEN }}
