name: Generate and deploy the docs to Pages

on:
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g openapi-merge-cli

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install pyyaml

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - run: curl https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.7.0/openapi-generator-cli-7.7.0.jar -o openapi-generator-cli.jar

      - name: Merge OpenAPI spec
        run: openapi-merge-cli --config ./rest/merge-config.json

      - name: Merge Doc spec
        run: python3 ./rest/script/yaml-merge.py ./rest/doc-api.yaml ./full-api.yaml /info > ./doc-full-api.yaml

      - name: Generate documentation
        run: |
          rm -rf docs
          java -jar openapi-generator-cli.jar generate -i doc-full-api.yaml -g html2 -o docs

      - name: Merge AWS spec
        run: python3 ./rest/script/yaml-merge.py ./rest/aws-api.yaml ./full-api.yaml x-amazon- > ./docs/merchant-v1.yaml

#      - name: Set up GitHub Pages
#        uses: actions/configure-pages@v5
#
#      - name: Upload artifact
#        uses: actions/upload-pages-artifact@v3
#        with:
#          path: './docs/'
#
#      - name: Deploy to GitHub Pages
#        uses: actions/deploy-pages@v4
